"""Type stubs for the C++ _corridors_mcts module."""
from typing import List, Tuple, Optional

class _corridors_mcts:
    """C++ MCTS implementation for Corridors game."""

    def __init__(
        self,
        c: float,
        seed: int,
        min_simulations: int,
        max_simulations: int,
        sim_increment: int,
        use_rollout: bool,
        eval_children: bool,
        use_puct: bool,
        use_probs: bool,
        decide_using_visits: bool,
    ) -> None: ...
    def make_move(self, action: str, flip: bool = False) -> None: ...
    def get_legal_moves(self, flip: bool = False) -> List[str]: ...
    def get_sorted_actions(
        self, flip: bool = False
    ) -> List[Tuple[int, float, str]]: ...
    def choose_best_action(self, epsilon: float = 0.0) -> str: ...
    def ensure_sims(self, num_sims: int) -> None: ...
    def get_evaluation(self) -> Optional[float]: ...
    def display(self, flip: bool = False) -> str: ...
    def reset(self) -> None: ...
    def is_terminal(self) -> bool: ...
    def get_winner(self) -> Optional[int]: ...
