"""Type stubs for requests.exceptions module."""

class RequestException(Exception): ...
class ConnectionError(RequestException): ...
class HTTPError(RequestException): ...
class Timeout(RequestException): ...
class TooManyRedirects(RequestException): ...
