[tool.poetry]
name = "mcts"
version = "0.1.0"
description = "Monte Carlo Tree Search implementation with C++ backend"
authors = ["Your Name <your.email@example.com>"]
readme = "README.md"
packages = [{include = "backend"}]


[tool.poetry.dependencies]
python = ">=3.12,<4.0"
pybind11 = ">=2.11.0,<3.0"
numpy = ">=1.26.3,<2.0"
pandas = ">=2.1.4,<3.0"
scipy = ">=1.11.4,<2.0"
torch = ">=2.1.2,<3.0"
torchvision = ">=0.16.2,<1.0"
pytorch-lightning = ">=2.1.3,<3.0"
dask = {extras = ["complete"], version = ">=2023.12.1,<2024.0"}
distributed = ">=2023.12.1,<2024.0"
numba = ">=0.58.1,<1.0"
plotly = ">=5.18.0,<6.0"
dash = ">=2.14.2,<3.0"
jupyter-dash = ">=0.4.2,<1.0"
jupyterlab = ">=3.6.6,<4.0"
ipywidgets = ">=8.1.1,<9.0"
tables = ">=3.9.2,<4.0"
pyarrow = ">=14.0.2,<15.0"
s3fs = ">=2023.12.2,<2024.0"
bokeh = ">=3.3.2,<4.0"
matplotlib-inline = ">=0.1.6,<1.0"
sympy = ">=1.12,<2.0"
networkx = ">=3.2.1,<4.0"
pillow = ">=10.2.0,<11.0"
requests = ">=2.31.0,<3.0"
aiohttp = ">=3.9.1,<4.0"
flask = ">=3.0.0,<4.0"
jinja2 = ">=3.1.2,<4.0"
pyyaml = ">=6.0.1,<7.0"
click = ">=8.1.7,<9.0"
tqdm = ">=4.66.1,<5.0"
psutil = ">=5.9.7,<6.0"
scons = ">=4.6.0,<5.0"

# API dependencies
fastapi = ">=0.109.0,<1.0"
uvicorn = {extras = ["standard"], version = ">=0.25.0,<1.0"}
pydantic = ">=2.5.3,<3.0"
websockets = ">=12.0,<13.0"
python-multipart = ">=0.0.6,<1.0"
httpx = ">=0.25.2,<1.0"

[tool.poetry.group.dev.dependencies]
mypy = ">=1.8.0,<2.0"
pandas-stubs = ">=2.1.4.231227,<3.0"
types-python-dateutil = ">=2.8.19.14,<3.0"
types-pytz = ">=2023.3.1.1,<2024.0"
pytest = ">=7.4.0,<8.0"
pytest-benchmark = ">=4.0.0,<5.0"
pytest-asyncio = ">=0.21.0,<1.0"
pytest-mock = ">=3.11.0,<4.0"
pytest-cov = ">=4.1.0,<5.0"
black = ">=23.7.0,<24.0"
isort = ">=5.12.0,<6.0"
flake8 = ">=6.0.0,<7.0"

[tool.poetry.group.cuda.dependencies]
# CUDA-specific dependencies for x86_64 systems
cupy-cuda12x = ">=12.3.0,<13.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ['py312']

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --strict-markers --strict-config"
testpaths = ["tests"]
asyncio_mode = "auto"
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests", 
    "cpp: marks tests that test C++ functionality via Python bindings",
    "python: marks tests that test pure Python functionality",
    "mcts: marks tests related to MCTS algorithm",
    "board: marks tests related to board functionality",
    "display: marks tests related to display/visualization",
    "performance: marks performance and stress tests",
    "edge_cases: marks edge case and boundary condition tests",
    "benchmark: marks tests as benchmarks (run with --benchmark-only)",
    "stress: marks stress tests with high resource usage",
    "api: marks tests related to the FastAPI server",
    "websocket: marks tests related to WebSocket functionality",
    "game_manager: marks tests related to game management",
    "models: marks tests related to Pydantic models",
    "endpoints: marks tests for API endpoints"
]
filterwarnings = [
    "ignore::UserWarning",
    "ignore::DeprecationWarning"
]

[tool.mypy]
python_version = "3.12"
strict = true
# Default paths to check
files = ["backend/", "tests/backend/"]
# Display options
show_error_codes = true
show_column_numbers = true
show_error_context = true
pretty = true
color_output = true
error_summary = true
# Reports disabled for now - can be enabled with lxml installed
# any_exprs_report = "mypy-reports"
# html_report = "mypy-reports/html"
# linecount_report = "mypy-reports/linecount"
# linecoverage_report = "mypy-reports/linecoverage"
# txt_report = "mypy-reports/txt"

# Pydantic BaseModel generates __mypy-replace methods that use Any internally
[[tool.mypy.overrides]]
module = "backend.api.models"
disable_error_code = "explicit-any"

# FastAPI generates decorators and uses Any internally  
[[tool.mypy.overrides]]
module = "backend.api.server"
disable_error_code = "misc"

# Python wrapper for C++ module - some Any usage is unavoidable
[[tool.mypy.overrides]]
module = "backend.python.corridors.corridors_mcts"
disable_error_code = "misc"

[tool.poetry.scripts]
api-server = "backend.api.server:main"
api-dev = "backend.api.server:dev"

# Test runners  
test-python = "tests.utils.run_tests:main"
test-python-api = "tests.utils.run_api_tests:main"
test-python-core = "tests.utils.run_core_tests:main"
test-all = "tests.utils.run_all_tests:main"
# Wrapper script for auto-installation
test-all-auto = "scripts.test-all:main"

[tool.poetry.extras]
api = ["fastapi", "uvicorn", "websockets", "python-multipart", "httpx"]

