version: '3.8'
services:
  mcts:
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        BASE_IMAGE: nvidia/cuda:12.2.2-runtime-ubuntu22.04
        REQUIREMENTS: ./docker/cuda/requirements.txt
    image: mcts_cuda
    platform: linux/amd64
    runtime: nvidia
    volumes:
      - ../..:/home/mcts
    ports:
      - "9888:8888"
      - "9786:8786"
      - "9787:8787"
    restart: unless-stopped
