version: '3.8'
services:
  mcts:
    build:
      context: ../..
      dockerfile: ./docker/Dockerfile
      args:
        BASE_IMAGE: ubuntu:22.04
        REQUIREMENTS: ./docker/arm/requirements.txt
    image: mcts_arm
    platform: linux/arm64
    volumes:
      - ../..:/home/mcts
    ports:
      - "9888:8888"
      - "9786:8786"
      - "9787:8787"
    restart: unless-stopped
