"""Type stubs for _pytest.config."""

from typing import Any, Dict, List, Optional

class Config:
    """Pytest configuration object."""

    option: "ArgparseNamespace"

    def __init__(self, pluginmanager: object) -> None: ...
    def getoption(self, name: str, default: object = ...) -> object: ...
    def getvalue(self, name: str) -> object: ...
    def addinivalue_line(self, section: str, line: str) -> None: ...

class ArgparseNamespace:
    """Namespace for parsed arguments."""

    def __init__(self) -> None: ...
    def __getattr__(self, name: str) -> object: ...
    def __setattr__(self, name: str, value: object) -> None: ...
    def __hasattr__(self, name: str) -> bool: ...
