complete -c mcts -f -a 'bench verify play inspect test lint docs commands help check-code build'
complete -c mcts -l backend -x -a 'cpp-legacy cpp-imperative cpp-functional rust haskell'
complete -c mcts -l vs -x -a 'cpp-legacy cpp-imperative cpp-functional rust haskell'
complete -c mcts -l rng -x -a 'native cpp'
complete -c mcts -l side -x -a 'hero villain'
complete -c mcts -l threading -x -a 'single multi'
complete -c mcts -l format -x -a 'json table plain'
complete -c mcts -l color -x -a 'auto always never'
complete -c mcts -n '__fish_seen_subcommand_from build' -a 'cpp-legacy cpp-imperative cpp-functional rust legacy-fixtures'
complete -c mcts -n '__fish_seen_subcommand_from test' -a 'mcts-haskell-style mcts-unit mcts-integration mcts-cross-backend mcts-legacy-parity mcts-semantic-parity'
