services:
  mcts:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VARIANT: cpu
        BASE_IMAGE: ubuntu:22.04
        USER_ID: 1000
        GROUP_ID: 1000
        USERNAME: mcts
    image: mcts:cpu
    user: "1000:1000"
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app/backend/python
      - NPM_CONFIG_YES=true
    volumes:
      # Mount entire project for live development
      - type: bind
        source: ..
        target: /app
        read_only: false
