volumes:
  frontend_build:
  backend_build:
  playwright_browsers:
  frontend_node_modules:
  frontend_test_node_modules:

services:
  mcts:
    container_name: mcts
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VARIANT: cpu
        BASE_IMAGE: ubuntu:22.04
    image: mcts:cpu
    pull_policy: never
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app/backend/python
      - NPM_CONFIG_YES=true
      - DOCKER_CONTAINER=1
    volumes:
      # Mount entire project for live development
      - type: bind
        source: ..
        target: /app
        read_only: false
      # Preserve frontend node_modules dependencies
      - type: volume
        source: frontend_node_modules
        target: /app/frontend/node_modules
      # Preserve frontend build artifacts
      - type: volume
        source: frontend_build
        target: /app/frontend/build
      # Preserve backend build artifacts (C++ extensions)
      - type: volume
        source: backend_build
        target: /app/backend/python/corridors
      # Preserve Playwright browser installations
      - type: volume
        source: playwright_browsers
        target: /root/.cache/ms-playwright
      # Preserve frontend test node_modules dependencies
      - type: volume
        source: frontend_test_node_modules
        target: /app/tests/frontend/node_modules
