services:
  mcts:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        BASE_IMAGE: ${BASE_IMAGE:-ubuntu:22.04}
    image: mcts:${TARGET:-cpu}
    runtime: ${RUNTIME:-}
    volumes:
      - type: bind
        source: ..
        target: /home/mcts
    ports:
      - target: 8000
        published: ${PORT:-8000}
        protocol: tcp
    restart: unless-stopped
    environment:
      PYTHONPATH: /home/mcts:/home/mcts/backend/python