services:
  mcts:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      platforms:
        - ${PLATFORM:-linux/amd64}
      args:
        TARGET: ${TARGET:-cpu}
    image: mcts:${TARGET:-cpu}
    ports:
      - target: 8000
        published: ${PORT:-8000}
        protocol: tcp
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app/backend/python
      - NPM_CONFIG_YES=true
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES:-void}
    volumes:
      # Bind mount source code but preserve built artifacts
      - type: bind
        source: ../backend/api
        target: /app/backend/api
        read_only: false
      - type: bind
        source: ../backend/core
        target: /app/backend/core
        read_only: false
      - type: bind
        source: ../backend/python/corridors/corridors_mcts.py
        target: /app/backend/python/corridors/corridors_mcts.py
        read_only: false
      - type: bind
        source: ../backend/python/corridors/__init__.py
        target: /app/backend/python/corridors/__init__.py
        read_only: false
      - type: bind
        source: ../backend/python/corridors/_corridors_mcts.pyi
        target: /app/backend/python/corridors/_corridors_mcts.pyi
        read_only: false
      # Note: Do NOT bind mount the .so file - let it stay from the image build
      # Bind mount tests
      - type: bind
        source: ../tests
        target: /app/tests
        read_only: false