volumes:
  frontend_build:
  backend_build:
  playwright_browsers:

services:
  mcts:
    container_name: mcts
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VARIANT: cpu
        BASE_IMAGE: ubuntu:22.04
        USER_ID: 1000
        GROUP_ID: 1000
        USERNAME: mcts
    image: mcts:cpu
    pull_policy: never
    user: "1000:1000"
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app/backend/python
      - NPM_CONFIG_YES=true
      - DOCKER_CONTAINER=1
    volumes:
      # Mount entire project for live development
      - type: bind
        source: ..
        target: /app
        read_only: false
      # Preserve frontend build artifacts
      - type: volume
        source: frontend_build
        target: /app/frontend/build
      # Preserve backend build artifacts (.so files)
      - type: volume
        source: backend_build
        target: /app/backend/python/corridors
        volume:
          nocopy: false
      # Preserve Playwright browser installations
      - type: volume
        source: playwright_browsers
        target: /home/mcts/.cache/ms-playwright
