version: '3.8'
services:
  mcts:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    image: mcts
    platform: linux/amd64
    runtime: nvidia
    volumes:
      - ../:/home/mcts
      - ../src:/home/python/corridors
    ports:
      - "8888:8888"
      - "8786:8786"
      - "8787:8787"
    restart: unless-stopped
