
services:
  mcts:
    container_name: mcts
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VARIANT: cpu
        BASE_IMAGE: ubuntu:22.04
    image: mcts:cpu
    pull_policy: never
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    restart: unless-stopped
    volumes:
      # Mount entire project for live development (git-versioned files only)
      - type: bind
        source: ..
        target: /app
        read_only: false
