services:
  mcts:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        TARGETARCH: ${TARGET:-cpu}
    image: mcts:${TARGET:-cpu}
    runtime: ${RUNTIME:-}
    volumes:
      - type: bind
        source: ..
        target: /home/mcts
    ports:
      - target: 8000
        published: ${PORT:-8000}
        protocol: tcp
    restart: unless-stopped
    environment:
      PYTHONPATH: /home/python/:/home/mcts/python/