services:
  mcts:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        VARIANT: cpu
        BASE_IMAGE: ubuntu:22.04
        USER_ID: 1000
        GROUP_ID: 1000
        USERNAME: mcts
    image: mcts:cpu
    pull_policy: build
    user: "1000:1000"
    ports:
      - target: 8000
        published: 8000
        protocol: tcp
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app/backend/python
      - NPM_CONFIG_YES=true
      - DOCKER_CONTAINER=1
    volumes:
      # Mount entire project for live development
      - type: bind
        source: ..
        target: /app
        read_only: false
      # Named volumes for build artifacts (preserves them across bind mounts)
      - frontend-build:/app/frontend/build
      - cpp-build:/app/backend/core
      - node-modules:/app/frontend/node_modules

volumes:
  frontend-build:
  cpp-build:
  node-modules:
