"""Type stubs for fastapi.websockets."""

from typing import Dict, List, Optional, Union
from starlette.websockets import WebSocket as StarletteWebSocket

_JsonValue = Union[
    None, bool, int, float, str, List["_JsonValue"], Dict[str, "_JsonValue"]
]

class WebSocket(StarletteWebSocket):
    async def accept(self) -> None: ...
    async def close(self, code: int = 1000) -> None: ...
    async def send_text(self, data: str) -> None: ...
    async def send_bytes(self, data: bytes) -> None: ...
    async def send_json(self, data: _JsonValue) -> None: ...
    async def receive_text(self) -> str: ...
    async def receive_bytes(self) -> bytes: ...
    async def receive_json(self) -> _JsonValue: ...
