"""Type stubs for websockets.client module."""

from typing import Optional, Union

class PingResponse:
    pass

class WebSocketClientProtocol:
    async def send(self, data: Union[str, bytes]) -> None: ...
    async def recv(self) -> str: ...
    async def close(self, code: Optional[int] = None, reason: str = "") -> None: ...
    async def ping(self, data: Optional[bytes] = None) -> PingResponse: ...
    async def pong(self, data: bytes = b"") -> None: ...
    async def __aenter__(self) -> "WebSocketClientProtocol": ...
    async def __aexit__(
        self, exc_type: object, exc_val: object, exc_tb: object
    ) -> None: ...
