"""Type stubs for websockets.exceptions."""

class WebSocketException(Exception): ...
class ConnectionClosed(WebSocketException): ...
class ConnectionClosedError(ConnectionClosed): ...
class ConnectionClosedOK(ConnectionClosed): ...
class InvalidHandshake(WebSocketException): ...
class InvalidURI(WebSocketException): ...
