"""Type stubs for click library."""
from typing import Callable, Optional, Union, TypeVar, overload

F = TypeVar("F")

class Group:
    def command(
        self, name: Optional[str] = None, **attrs: object
    ) -> Callable[[F], F]: ...
    def __call__(self) -> None: ...

def group(name: Optional[str] = None, **attrs: object) -> Callable[[F], Group]: ...
def command(name: Optional[str] = None, **attrs: object) -> Callable[[F], F]: ...
@overload
def option(param_decl: str, **attrs: object) -> Callable[[F], F]: ...
@overload
def option(*param_decls: str, **attrs: object) -> Callable[[F], F]: ...
@overload
def argument(param_decl: str, **attrs: object) -> Callable[[F], F]: ...
@overload
def argument(*param_decls: str, **attrs: object) -> Callable[[F], F]: ...
def echo(message: Optional[object], **kwargs: object) -> None: ...
