"""Type stubs for psutil module."""

from typing import Dict, Iterator, List, Optional, Union

class Process:
    def __init__(self, pid: Optional[int] = None) -> None: ...
    @property
    def pid(self) -> int: ...
    @property
    def info(self) -> Dict[str, Union[int, str, List[str]]]: ...
    def connections(self) -> List[Connection]: ...
    def name(self) -> str: ...
    def cmdline(self) -> List[str]: ...
    def kill(self) -> None: ...
    def terminate(self) -> None: ...

class Connection:
    @property
    def laddr(self) -> Address: ...
    @property
    def raddr(self) -> Optional[Address]: ...

class Address:
    @property
    def ip(self) -> str: ...
    @property
    def port(self) -> int: ...

class NoSuchProcess(Exception): ...
class AccessDenied(Exception): ...
class ZombieProcess(Exception): ...

def process_iter(attrs: Optional[List[str]] = None) -> Iterator[Process]: ...
