"""Type stubs for corridors module."""

from typing import Optional, List, Tuple, Dict, Protocol

class CorridorsMCTSProtocol(Protocol):
    """Protocol for Corridors_MCTS interface."""

    def make_move(self, action: str, flip: bool = False) -> None: ...
    def get_legal_moves(self, flip: bool = False) -> List[str]: ...
    def get_sorted_actions(
        self, flip: bool = False
    ) -> List[Tuple[int, float, str]]: ...
    def choose_best_action(self, epsilon: float = 0.0) -> str: ...
    def ensure_sims(self, num_sims: int) -> None: ...
    def get_evaluation(self) -> Optional[float]: ...
    def display(self, flip: bool = False) -> str: ...
    def reset(self) -> None: ...
    def is_terminal(self) -> bool: ...
    def get_winner(self) -> Optional[int]: ...
    def get_best_move(self) -> str: ...
    def get_action_stats(self) -> Dict[str, Dict[str, float]]: ...
