"""Stub file for the C++ _corridors_mcts extension module."""

from typing import List, Optional, Tuple

class _corridors_mcts:
    """C++ MCTS implementation."""

    def __init__(
        self,
        c: float,
        seed: int,
        use_rollout: bool,
        eval_children: bool,
        use_puct: bool,
        use_probs: bool,
        decide_using_visits: bool,
    ) -> None: ...
    def run_simulations(self, n: int) -> None: ...
    def make_move(self, action: str, flip: bool = False) -> None: ...
    def get_sorted_actions(
        self, flip: bool = False
    ) -> List[Tuple[int, float, str]]: ...
    def choose_best_action(self, epsilon: float = 0.0) -> str: ...
    def get_evaluation(self) -> Optional[float]: ...
    def get_visit_count(self) -> int: ...
    def display(self, flip: bool = False) -> str: ...
    def reset_to_initial_state(self) -> None: ...
    def is_terminal(self) -> bool: ...
